### ISSUE TITLE
Support buffers instead of filepaths

### ISSUE THREAD

**Issue by tmcw** [twolfson/spritesmith-engine-test#1]
I'm looking to support a usecase in which image data is loaded as a buffer from a database and sprited per-request. In the meantime, I can support this by writing tmp files and giving spritesmith the paths, but it would be great if there was an option to give id->buffer mappings rather than file paths as input.

**Comment by twolfson** [comment]
Let's use Ensighten/spritesmith#51 as the common thread for this discussion.
